[tool.black]
line-length = 120
target-version = ["py310"]
exclude = '''
(
    \.venv
    | __pycache__
    | build
    | dist
)
'''

[tool.isort]
profile = "black"
line_length = 120
skip = [".venv", "__pycache__", "build", "dist"]

[tool.flake8]
max-line-length = 120
extend-ignore = [
    "E203",
    "W503", 
]
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist"
]
